/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package biz.di.groovy

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'biz.di.groovy.greeting' plugin.
 */
class Groovy2jsPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("biz.di.groovy.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
